version: '3.8'

services:
  backend:
    build: ./app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:26257/wellness?sslmode=disable
    depends_on:
      - db

  frontend:
    build: ./app/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach-data: 